def build_expert_search_reasoning_prompt(sota_md: str, thesis_desc: str, thesis_thoughts: list[str], expert_context: dict) -> str:
    # Format thesis thoughts as a bulleted list if there are any
    formatted_thoughts = ""
    if thesis_thoughts:
        formatted_thoughts = "Thoughts:\n" + "\n".join([f"- {thought}" for thought in thesis_thoughts])
    else:
        formatted_thoughts = "No additional thesis thoughts provided."
    
    return (
        f"# Current State-of-the-Art (SOTA) Table\n{sota_md}\n\n"
        f"# Thesis Knowledge\nDescription: {thesis_desc}\n{formatted_thoughts}\n\n"
        f"# Expert Analysis Task\n"
        f"Analyze the gaps between the current SOTA table and the thesis requirements. For each expert in the provided context, "
        f"determine what critical information is missing from the current SOTA table that would strengthen the thesis analysis.\n\n"
        f"## Instructions:\n"
        f"1. Carefully evaluate the areas where the SOTA table lacks sufficient depth, breadth, or specific technical details needed for the thesis.\n"
        f"2. Identify the most important missing information categories (methodologies, performance metrics, dataset comparisons, etc.).\n"
        f"3. For each expert, structure your analysis to cover the research space hierarchically:\n"
        f"   - FOUNDATIONAL: First identify fundamental papers and core concepts essential to the field\n" 
        f"   - ESTABLISHED: Then focus on established methodologies and key technical approaches\n"
        f"   - SPECIALIZED: Finally address cutting-edge advances and specialized techniques\n"
        f"4. Suggest concrete search queries using precise technical terminology for each level of depth.\n"
        f"5. Prioritize searches that provide a progression from theoretical foundations to practical applications.\n"
        f"6. Focus on specific technical aspects rather than general topics.\n"
        f"7. Ensure coverage from seminal works to the latest innovations in your recommendations.\n\n"
        f"## Response Format (for each expert):\n"
        f"- **Gap Analysis**: What critical information is missing from the current SOTA table?\n"
        f"- **Reasoning**: Why is this information important for the thesis?\n"
        f"- **Foundational Search**: Search terms for fundamental papers and core concepts\n"
        f"- **Established Methods Search**: Search terms for established methodologies and techniques\n"
        f"- **Specialized Search**: Search terms for cutting-edge advances and specialized approaches\n"
        f"- **Expected Impact**: How will filling this gap strengthen the thesis analysis?\n\n"
        f"## Example Expert Analysis:\n\n"
        f"### Machine Learning Expert Example\n"
        f"**Gap Analysis**: The SOTA table lacks experimental comparisons of transformer architectures on multi-modal datasets.\n"
        f"**Reasoning**: Understanding how different transformer variants perform on combined text-image tasks is crucial for evaluating their generalizability beyond single-modality performance.\n"
        f"**Foundational Search**: \"transformer architecture original paper attention mechanism theory\"\n"
        f"**Established Methods Search**: \"vision-language transformers multi-modal fusion techniques\"\n"
        f"**Specialized Search**: \"transformer architecture benchmarks multi-modal performance comparison efficiency metrics\"\n"
        f"**Expected Impact**: Adding this information will provide a comprehensive understanding from theoretical foundations to practical implementation, with quantitative evidence for which architectures are most suitable for the thesis's proposed multi-modal application.\n\n"
        f"### Natural Language Processing Expert Example\n"
        f"**Gap Analysis**: The current SOTA table doesn't include information about few-shot learning capabilities of large language models for domain-specific tasks.\n"
        f"**Reasoning**: Understanding few-shot performance is critical for applications where labeled training data is scarce, as is the case in the specialized domain of the thesis.\n"
        f"**Foundational Search**: \"language model pretraining transfer learning foundations theoretical principles\"\n"
        f"**Established Methods Search**: \"few-shot learning techniques prompt engineering language models\"\n"
        f"**Specialized Search**: \"large language models few-shot learning specialized domains performance metrics comparison\"\n"
        f"**Expected Impact**: Building this knowledge progressively will provide both theoretical understanding and practical evidence for assessing the feasibility of using pre-trained models with minimal fine-tuning for the thesis application.\n\n"
        f"### Computer Vision Expert Example\n"
        f"**Gap Analysis**: The SOTA table lacks analysis of computational efficiency metrics for real-time object detection algorithms on edge devices.\n"
        f"**Reasoning**: For the thesis's proposed deployment scenario on resource-constrained devices, understanding the speed-accuracy tradeoffs is essential.\n"
        f"**Foundational Search**: \"object detection algorithms fundamental principles accuracy metrics\"\n"
        f"**Established Methods Search**: \"lightweight object detection architectures model compression techniques\"\n"
        f"**Specialized Search**: \"object detection edge computing latency power consumption benchmarks real-time performance\"\n"
        f"**Expected Impact**: This layered knowledge approach will build from core principles to practical implementations, enabling an informed selection of algorithms that meet both the accuracy requirements and the hardware constraints of the target deployment.\n\n"
        f"## Available Experts:\n{expert_context}\n"
    )
